import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Head } from "@/components/ui/Head";
import Footer from "@/components/Footer";
import { ThemeProvider } from "@/components/Theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className=" bg-slate-100 dark:bg-slate-900">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <Head />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
